services:
  mysql:
    image: mysql:8.0
    container_name: fs-store-mysql
    restart: always
    env_file: 
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "33306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fs-network

  migrator:
    build:
      context: ./migration
      dockerfile: Dockerfile
    container_name: fs-store-migrate
    env_file: 
      - ./.env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    volumes:
      - ./db/migrations:/app/db/migrations
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fs-network

  file-store:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fs-store-server
    restart: always
    env_file: 
      - ./.env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - BASE_STORAGE_DIR=${BASE_STORAGE_DIR}
    ports:
      - "38080:${PORT}"
    volumes:
      - file-store-storage:${BASE_STORAGE_DIR}
    depends_on:
      migrator:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
    networks:
      - fs-network

volumes:
  mysql-data:
  file-store-storage:

networks:
  fs-network:
    driver: bridge 