# .air.toml

root = "."
tmp_dir = "tmp" # Temporary directory for compiled binaries

[build]
# Command to build your Go application.
# `.` refers to the current directory (your project root inside the container).
cmd = "go build -o ./tmp/main ./cmd"
# The binary that Air should run. This should match the output of your build command.
bin = "./tmp/main"
# Delay in milliseconds before restarting the application after a file change.
# Adjust if you find it's too aggressive or not quick enough.
delay = 1000
# Directories to exclude from triggering a rebuild.
# Always exclude `tmp` and `vendor` (if you're using vendor modules).
exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git", ".idea", "node_modules"]
# File extensions to include for watching. Add others if you have config files, templates, etc.
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "json", "yaml", "yml"]

[run]
# Arguments to pass to your compiled binary.
args = []

[log]
# Customize log output colors (optional)
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
# Clean up the tmp directory on exit.
clean_on_exit = true
