// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/spf13/cobra"
	"github.com/tomoya.tokunaga/cli/internal/di"
)

// Injectors from wire.go:

// InitializeApplication initializes the CLI application with dependency injection
func InitializeApplication() (*Application, error) {
	initUploadUsecase := di.InitUploadUsecaseProvider()
	uploadUsecase := di.UploadUsecaseProvider()
	deleteUsecase := di.DeleteFileUsecaseProvider()
	uploadCommand := di.UploadCommandProvider(initUploadUsecase, uploadUsecase, deleteUsecase)
	deleteCommand := di.DeleteCommandProvider(deleteUsecase)
	listUsecase := di.ListUsecaseProvider()
	listCommand := di.ListCommandProvider(listUsecase)
	command := di.RootCommandProvider(uploadCommand, deleteCommand, listCommand)
	application := &Application{
		RootCmd: command,
	}
	return application, nil
}

// wire.go:

// Application holds the CLI application
type Application struct {
	RootCmd *cobra.Command
}

// Run executes the root command
func (app *Application) Run() error {
	return app.RootCmd.Execute()
}
