// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/tomoya.tokunaga/server/internal/core/entity"
	"github.com/tomoya.tokunaga/server/internal/di"
	"github.com/tomoya.tokunaga/server/internal/interface/api/router"
	"golang.org/x/exp/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"
)

// Injectors from wire.go:

// InitializeApplication initializes all application components
func InitializeApplication() (*Application, error) {
	config := di.ConfigProvider()
	logger := di.LoggerProvider()
	db, err := di.DBProvider(config, logger)
	if err != nil {
		return nil, err
	}
	fileRepository := di.FileRepositoryProvider(db)
	fileChunkRepository := di.FileChunkRepositoryProvider(db)
	storageRepository := di.StorageRepositoryProvider()
	fileUseCase := di.FileUseCaseProvider(fileRepository, fileChunkRepository, storageRepository, config)
	fileHandler := di.FileHandlerProvider(fileUseCase, logger)
	router := di.RouterProvider(fileHandler)
	server := HTTPServerProvider(config, router)
	application := &Application{
		Config: config,
		Logger: logger,
		Router: router,
		Server: server,
	}
	return application, nil
}

// wire.go:

// Application holds all the components needed for application
type Application struct {
	Config *entity.Config
	Logger *slog.Logger
	Router *router.Router
	Server *http.Server
}

// HTTPServerProvider provides the configured HTTP server
func HTTPServerProvider(config *entity.Config, router2 *router.Router) *http.Server {
	r := router2.Engine()

	r.MaxMultipartMemory = int64(config.MaxBodySize)

	return &http.Server{
		Addr:    fmt.Sprintf(":%d", config.Port),
		Handler: r,
	}
}

// Run starts the application and handles graceful shutdown
func (app *Application) Run() error {

	go func() {
		app.Logger.Info("starting server", "addr", app.Server.Addr)
		if err := app.Server.ListenAndServe(); err != nil {
			if err.Error() != "http: Server closed" {
				app.Logger.Error("server error", "error", err)
				os.Exit(1)
			}
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	app.Logger.Info("shutting down server...")

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := app.Server.Shutdown(ctx); err != nil {
		app.Logger.Error("server forced to shutdown", "error", err)
		return err
	}

	app.Logger.Info("server exited gracefully")
	return nil
}
